# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeviceEnumsProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DeviceEnumsProto.proto',
  package='net.device',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x44\x65viceEnumsProto.proto\x12\nnet.device*8\n\x13MastershipRoleProto\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06MASTER\x10\x01\x12\x0b\n\x07STANDBY\x10\x02*\xca\x01\n\x0f\x44\x65viceTypeProto\x12\t\n\x05OTHER\x10\x00\x12\n\n\x06SWITCH\x10\x01\x12\n\n\x06ROUTER\x10\x02\x12\t\n\x05ROADM\x10\x03\x12\x07\n\x03OTN\x10\x04\x12\r\n\tROADM_OTN\x10\x05\x12\x0c\n\x08\x46IREWALL\x10\x06\x12\x0c\n\x08\x42\x41LANCER\x10\x07\x12\x07\n\x03IPS\x10\x08\x12\x07\n\x03IDS\x10\t\x12\x0e\n\nCONTROLLER\x10\n\x12\x12\n\x0eVIRTUAL_DEVICE\x10\x0b\x12\x10\n\x0c\x46IBER_SWITCH\x10\x0c\x12\r\n\tMICROWAVE\x10\r*\xd3\x01\n\x14\x44\x65viceEventTypeProto\x12\x10\n\x0c\x44\x45VICE_ADDED\x10\x00\x12\x12\n\x0e\x44\x45VICE_UPDATED\x10\x01\x12\x12\n\x0e\x44\x45VICE_REMOVED\x10\x02\x12\x14\n\x10\x44\x45VICE_SUSPENDED\x10\x03\x12\x1f\n\x1b\x44\x45VICE_AVAILABILITY_CHANGED\x10\x04\x12\x0e\n\nPORT_ADDED\x10\x05\x12\x10\n\x0cPORT_UPDATED\x10\x06\x12\x10\n\x0cPORT_REMOVED\x10\x07\x12\x16\n\x12PORT_STATS_UPDATED\x10\x08\x42(\n&org.onosproject.grpc.net.device.modelsb\x06proto3')
)

_MASTERSHIPROLEPROTO = _descriptor.EnumDescriptor(
  name='MastershipRoleProto',
  full_name='net.device.MastershipRoleProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MASTER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STANDBY', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=38,
  serialized_end=94,
)
_sym_db.RegisterEnumDescriptor(_MASTERSHIPROLEPROTO)

MastershipRoleProto = enum_type_wrapper.EnumTypeWrapper(_MASTERSHIPROLEPROTO)
_DEVICETYPEPROTO = _descriptor.EnumDescriptor(
  name='DeviceTypeProto',
  full_name='net.device.DeviceTypeProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SWITCH', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROUTER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROADM', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTN', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROADM_OTN', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIREWALL', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BALANCER', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IPS', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IDS', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTROLLER', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIRTUAL_DEVICE', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIBER_SWITCH', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICROWAVE', index=13, number=13,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=97,
  serialized_end=299,
)
_sym_db.RegisterEnumDescriptor(_DEVICETYPEPROTO)

DeviceTypeProto = enum_type_wrapper.EnumTypeWrapper(_DEVICETYPEPROTO)
_DEVICEEVENTTYPEPROTO = _descriptor.EnumDescriptor(
  name='DeviceEventTypeProto',
  full_name='net.device.DeviceEventTypeProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEVICE_ADDED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_UPDATED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_REMOVED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_SUSPENDED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_AVAILABILITY_CHANGED', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PORT_ADDED', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PORT_UPDATED', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PORT_REMOVED', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PORT_STATS_UPDATED', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=302,
  serialized_end=513,
)
_sym_db.RegisterEnumDescriptor(_DEVICEEVENTTYPEPROTO)

DeviceEventTypeProto = enum_type_wrapper.EnumTypeWrapper(_DEVICEEVENTTYPEPROTO)
NONE = 0
MASTER = 1
STANDBY = 2
OTHER = 0
SWITCH = 1
ROUTER = 2
ROADM = 3
OTN = 4
ROADM_OTN = 5
FIREWALL = 6
BALANCER = 7
IPS = 8
IDS = 9
CONTROLLER = 10
VIRTUAL_DEVICE = 11
FIBER_SWITCH = 12
MICROWAVE = 13
DEVICE_ADDED = 0
DEVICE_UPDATED = 1
DEVICE_REMOVED = 2
DEVICE_SUSPENDED = 3
DEVICE_AVAILABILITY_CHANGED = 4
PORT_ADDED = 5
PORT_UPDATED = 6
PORT_REMOVED = 7
PORT_STATS_UPDATED = 8


DESCRIPTOR.enum_types_by_name['MastershipRoleProto'] = _MASTERSHIPROLEPROTO
DESCRIPTOR.enum_types_by_name['DeviceTypeProto'] = _DEVICETYPEPROTO
DESCRIPTOR.enum_types_by_name['DeviceEventTypeProto'] = _DEVICEEVENTTYPEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n&org.onosproject.grpc.net.device.models'))
# @@protoc_insertion_point(module_scope)
