# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PortEnumsProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PortEnumsProto.proto',
  package='net.device',
  syntax='proto3',
  serialized_pb=_b('\n\x14PortEnumsProto.proto\x12\nnet.device*b\n\rPortTypeProto\x12\n\n\x06\x43OPPER\x10\x00\x12\t\n\x05\x46IBER\x10\x01\x12\n\n\x06PACKET\x10\x02\x12\n\n\x06ODUCLT\x10\x03\x12\x07\n\x03OCH\x10\x04\x12\x07\n\x03OMS\x10\x05\x12\x10\n\x0cVIRTUAL_PORT\x10\x06\x42(\n&org.onosproject.grpc.net.device.modelsb\x06proto3')
)

_PORTTYPEPROTO = _descriptor.EnumDescriptor(
  name='PortTypeProto',
  full_name='net.device.PortTypeProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COPPER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIBER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PACKET', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ODUCLT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OCH', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OMS', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIRTUAL_PORT', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=36,
  serialized_end=134,
)
_sym_db.RegisterEnumDescriptor(_PORTTYPEPROTO)

PortTypeProto = enum_type_wrapper.EnumTypeWrapper(_PORTTYPEPROTO)
COPPER = 0
FIBER = 1
PACKET = 2
ODUCLT = 3
OCH = 4
OMS = 5
VIRTUAL_PORT = 6


DESCRIPTOR.enum_types_by_name['PortTypeProto'] = _PORTTYPEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n&org.onosproject.grpc.net.device.models'))
# @@protoc_insertion_point(module_scope)
