# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PortProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PortEnumsProto_pb2 as PortEnumsProto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PortProto.proto',
  package='net',
  syntax='proto3',
  serialized_pb=_b('\n\x0fPortProto.proto\x12\x03net\x1a\x14PortEnumsProto.proto\"\xdb\x01\n\tPortProto\x12\x13\n\x0bport_number\x18\x01 \x01(\t\x12\x12\n\nis_enabled\x18\x02 \x01(\x08\x12\'\n\x04type\x18\x03 \x01(\x0e\x32\x19.net.device.PortTypeProto\x12\x12\n\nport_speed\x18\x04 \x01(\x03\x12\x34\n\x0b\x61nnotations\x18\x05 \x03(\x0b\x32\x1f.net.PortProto.AnnotationsEntry\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42!\n\x1forg.onosproject.grpc.net.modelsb\x06proto3')
  ,
  dependencies=[PortEnumsProto__pb2.DESCRIPTOR,])




_PORTPROTO_ANNOTATIONSENTRY = _descriptor.Descriptor(
  name='AnnotationsEntry',
  full_name='net.PortProto.AnnotationsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='net.PortProto.AnnotationsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='net.PortProto.AnnotationsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=266,
)

_PORTPROTO = _descriptor.Descriptor(
  name='PortProto',
  full_name='net.PortProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port_number', full_name='net.PortProto.port_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_enabled', full_name='net.PortProto.is_enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='net.PortProto.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port_speed', full_name='net.PortProto.port_speed', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='annotations', full_name='net.PortProto.annotations', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PORTPROTO_ANNOTATIONSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=266,
)

_PORTPROTO_ANNOTATIONSENTRY.containing_type = _PORTPROTO
_PORTPROTO.fields_by_name['type'].enum_type = PortEnumsProto__pb2._PORTTYPEPROTO
_PORTPROTO.fields_by_name['annotations'].message_type = _PORTPROTO_ANNOTATIONSENTRY
DESCRIPTOR.message_types_by_name['PortProto'] = _PORTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PortProto = _reflection.GeneratedProtocolMessageType('PortProto', (_message.Message,), dict(

  AnnotationsEntry = _reflection.GeneratedProtocolMessageType('AnnotationsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PORTPROTO_ANNOTATIONSENTRY,
    __module__ = 'PortProto_pb2'
    # @@protoc_insertion_point(class_scope:net.PortProto.AnnotationsEntry)
    ))
  ,
  DESCRIPTOR = _PORTPROTO,
  __module__ = 'PortProto_pb2'
  # @@protoc_insertion_point(class_scope:net.PortProto)
  ))
_sym_db.RegisterMessage(PortProto)
_sym_db.RegisterMessage(PortProto.AnnotationsEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037org.onosproject.grpc.net.models'))
_PORTPROTO_ANNOTATIONSENTRY.has_options = True
_PORTPROTO_ANNOTATIONSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
